INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES() 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES 