INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Harry Potter", "Movie", 500, "01/16/22", "01/22/22"); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Toys", "Donation", 1000, "/05/17/20", "05/30/20"); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Plantating trees", "Echology", 2500, "06/02/20", "10/20/20") ;
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Movie in the park", "Movie", 8, "05/20/20", "08/20/20"); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Saving the light", "Echologic", 1, "04/05/21", "04/06/21"); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Picking the coffee", "Coffee feelds", 200, "05/13/20", "11/22/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food for holess", "Donation", 300, "07/01/22", "08/30/22"); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hospital blankets", "Donation", 1500, "04/22/21", "09/30/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean cleaning", "Echologiy", 5000, "10/22/20", "11/30/21" );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ironman", "Sports", 1000, "08/12/20", "08/20/20");


INSERT INTO users (name, age) VALUES ("Catie", 34);
INSERT INTO users (name, age) VALUES ("Tom", 36);
INSERT INTO users (name, age) VALUES ("Thomas", 24);
INSERT INTO users (name, age) VALUES ("Alberto", 48);
INSERT INTO users (name, age) VALUES ("John", 52);
INSERT INTO users (name, age) VALUES ("Dani", 22);
INSERT INTO users (name, age) VALUES ("Juan", 30);
INSERT INTO users (name, age) VALUES ("Natalia", 29);
INSERT INTO users (name, age) VALUES ("Pedro", 39);
INSERT INTO users (name, age) VALUES ("Nick", 38);
INSERT INTO users (name, age) VALUES ("Kevin", 33);
INSERT INTO users (name, age) VALUES ("Lisa", 43);
INSERT INTO users (name, age) VALUES ("Angie", 34);
INSERT INTO users (name, age) VALUES ("Omar", 27);
INSERT INTO users (name, age) VALUES ("Jimmy", 55);
INSERT INTO users (name, age) VALUES ("Andreas", 24);
INSERT INTO users (name, age) VALUES ("Eliot", 50);
INSERT INTO users (name, age) VALUES ("Jeff", 40);
INSERT INTO users (name, age) VALUES ("Rick", 38);
INSERT INTO users (name, age) VALUES ("Isabela", 35);


INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 10);